# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/vendor/cirrus/modules/include
EXTRA_CFLAGS += -DCONFIG_SND_SOC_MADERA_SLIMBUS

EXTRA_CFLAGS += -DCONFIG_SND_SOC_MADERA_SLIMBUS
cirrus_madera-objs = madera.o madera-slimbus.o wm_adsp.o
obj-m += cirrus_madera.o

cirrus_cs47l35-objs =  cs47l35.o
obj-m += cirrus_cs47l35.o

cirrus_cs35l41_spi-objs = cs35l41.o cs35l41-tables.o cs35l41-spi.o
obj-m += cirrus_cs35l41_spi.o

cirrus_cs35l41_i2c-objs = cs35l41.o cs35l41-tables.o cs35l41-i2c.o
obj-m += cirrus_cs35l41_i2c.o
