# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/vendor/cirrus/modules/include

obj-m += arizona-ldo1.o arizona-micsupp.o
#obj-m += madera-ldo1.o madera-micsupp.o
